CREATE DATABASE IF4101_LAB1_B97452
GO 

USE IF4101_LAB1_B97452
GO

CREATE SCHEMA COUNTRIES
GO

CREATE SCHEMA CURRENCY
GO

CREATE TABLE CURRENCY.tb_CURRENCY
(
	 CURRENCY_ID   INT IDENTITY(1,1) PRIMARY KEY 
	,CURRENCY_NAME VARCHAR(50) NOT NULL
	,DOLLAR_VALUE  DECIMAL(10,5) NOT NULL
)

CREATE TABLE COUNTRIES.tb_COUNTRY
(
	 COUNTRY_ID   INT IDENTITY(1,1) PRIMARY KEY 
	,CURRENCY_ID  INT				NOT NULL
	,COUNTRY_NAME VARCHAR(50)		NOT NULL
	,CONSTRAINT FK_COUNTRY_CURRENCY FOREIGN KEY(CURRENCY_ID)
		REFERENCES CURRENCY.tb_CURRENCY(CURRENCY_ID)
)