CREATE PROCEDURE CURRENCY.sp_GET_DOLLAR_VALUE_CURRENCY @COUNTRY_NAME VARCHAR(50)
AS
BEGIN
SELECT 
	[DOLLAR_VALUE]
FROM [CURRENCY].[tb_CURRENCY] CRRY
	JOIN [COUNTRIES].[tb_COUNTRY] CTY
		ON CTY.CURRENCY_ID = CRRY.CURRENCY_ID
WHERE CTY.COUNTRY_NAME = @COUNTRY_NAME
END